/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT010aG5ndjVFdGRBR0wxM3dVTmJZemx2R3BsMlJ4SklpYzNJcDJNbGIzOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib08wY3F1UWZ0RDFpRllzUVJsSVBBdzhEREVSMFo3ZjZyT2JjWWtZdVRWVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTUGk2czJkbm4xUThUVWh4VldTZ0c5b2pLSENNaEV3QUttZnZKbGlQcEY0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI3WGtWMTZoYXNsaGhaTlhqbkJlaUNGYVlZTjJnRTNPMHd1YmhkMDNISnpjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklCSGxEckxlc1dQb1I5VUE2V2xWWmVHak5KOGYrWlg4RTZ2QWF3eWovbE09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjVYQU5iQlRVOFo3WFlsWkpGdkJQbHJjUWtjc0Uyd0VSSGJ2NkJSUHRzUVE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibURNNEJPWHdCcHNhUWRPVkNaM3RPN2pMRDhkK09ycGpseVM2Ny95VUNVMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV3N6UUZ0N2UvQ1IwTTRoOHNIcW82b2UxZlRuc3FLclNiSWY0RmtySjBTQT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktZVXZDNnRPS3V5aEFjSEd3TWNXaEdyRVE2QURCNXByVmlNdDhKV2FpVDFnczYvUkpqblJPeXpqaG5Xa1hxSkFWZFl2U0Y2b0pBL1l4SlFRZm1TUGpnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTI3LCJhZHZTZWNyZXRLZXkiOiIzTXl3MU9Pd1hVb251dDI0NnNGcndMUHBWNmMzbjRUVE5TRGlBK3FRRXQwPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJRQWxWQzA1ZVNHYVowa09vTlZHWGZ3IiwicGhvbmVJZCI6IjhmNmNmMjIxLTc1MDMtNGZmMi05MjI0LTljYWZlM2QwMjBlOCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJoOFZUc0lTek9NdXJLTXB1b3ZmV2psNW9yVzg9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOTQyTzRZMkVLUlBiQW53WndsQU9WeVduR3NzPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlBEVFJKUUZaIiwibWUiOnsiaWQiOiI5NDc4OTMxMjM1Nzo3N0BzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJIeSBoeSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDS1BXMGJBSEVJWHAzTGtHR0FZZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiNldmNUNjSEtaSytRRUN6M1BuMy9zaDZBZDd0UDFVQXIxQ0lqNTBxYkV5RT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiNXpYYU1Tc3pCRnRXcjFlOUhSenhpMkNaRzBZQlNhS29LN1IvT2wvU3lGR04rc1JnVGJTMkRUYXhrNnpPRm8yR2hUL29wVWh1STJjVnh6N3JwMXdOQnc9PSIsImRldmljZVNpZ25hdHVyZSI6IjI4UjdvZGN4WEMxZ3ptU2JlZDA1L09NMGQ3NzBPRjZrYmhpOGpHQnYybTMzOElEWXhucWxSa1Z6TnpoY0FBajlXUS8xaDFMZUdtTFd4aTAxT1lJVmhBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTQ3ODkzMTIzNTc6NzdAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZWxuK1FuQnltU3ZrQkFzOXo1OS83SWVnSGU3VDlWQUs5UWlJK2RLbXhNaCJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMTY3MTE4Nn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝙰𝙺𝙸𝙾-𝙼𝙳';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
